FORMAT: 1A
HOST: https://letsintegrate.de/api

# Let's integrate


# Group Location

## GET /v1/locations(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + location (optional, string, `{}`) ...
    + ids (optional, string, `e17df1ab-81ca-4731-b502-0ac6f1a76cf9`) ...
    + filter (optional, string, `{"offer_locations_offer_id_eq"=>"b2512439-1fbf-4b6d-80c5-114748d2db47"}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"346666fb9207f18f13b5008a6416ccb1"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 5518d32e-18d1-4610-b46f-ab75cbfd1044
            X-Runtime: 0.582493
            Content-Length: 387

    + Body

            {"data":[{"id":"429f90d5-cc24-4334-9f35-5efcb2239196","type":"locations","attributes":{"name":"Location 01","images":["http://lorempixel.com/800/600/city/1/","http://lorempixel.com/800/600/city/3/"],"slug":"location-01"},"relationships":{"offers":{"links":{"related":"http://www.example.com/v1/offers?filter%5Boffer_locations_location_id_eq%5D=429f90d5-cc24-4334-9f35-5efcb2239196"}}}}]}

## GET /v1/locations/{id}(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + id (required, string, `23836342-47ec-421c-9b09-737e0a1b621f`) ...
    + location (optional, string, `{}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"b9a691e1f0dac8c69781b59c8b0e47bb"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: e78d0c76-f721-4011-962b-30eb856c2a9c
            X-Runtime: 0.006718
            Content-Length: 385

    + Body

            {"data":{"id":"23836342-47ec-421c-9b09-737e0a1b621f","type":"locations","attributes":{"name":"Location 05","images":["http://lorempixel.com/800/600/city/1/","http://lorempixel.com/800/600/city/3/"],"slug":"location-05"},"relationships":{"offers":{"links":{"related":"http://www.example.com/v1/offers?filter%5Boffer_locations_location_id_eq%5D=23836342-47ec-421c-9b09-737e0a1b621f"}}}}}

# Group OfferTime

## GET /v1/offer_times(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + offer_time (optional, string, `{}`) ...
    + ids (optional, string, `3c9cfbbd-707e-45e9-90dd-1a466d3dd050`) ...
    + filter (optional, string, `{"offer_id_eq"=>"b5bbff48-ce87-41d8-984b-fb1fb2b5d947"}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"3178285eb8666cf5d77b077a95c1046b"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 9a4d508b-b4d6-48c7-a221-2332eba978ef
            X-Runtime: 0.206906
            Content-Length: 246

    + Body

            {"data":[{"id":"944e3618-c402-4394-9816-bd3f03f96576","type":"offer-times","attributes":{"time":"2012-05-07T00:00:00.000Z"},"relationships":{"offer":{"links":{"related":"http://www.example.com/v1/offers/030ba4d3-d6ee-4805-afa7-b1924eced6db"}}}}]}

## GET /v1/offer_times/{id}(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + id (required, string, `62bd876c-8607-457f-b870-cfadcfa966fb`) ...
    + offer_time (optional, string, `{}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"e82cfb136d15e8d69aa638734c576237"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: a21cb13b-32c4-4b34-a8a8-474cf1a223b5
            X-Runtime: 0.017318
            Content-Length: 244

    + Body

            {"data":{"id":"62bd876c-8607-457f-b870-cfadcfa966fb","type":"offer-times","attributes":{"time":"2013-01-24T00:00:00.000Z"},"relationships":{"offer":{"links":{"related":"http://www.example.com/v1/offers/6bb68d1d-7170-435e-b84b-0cbeb9c20eb0"}}}}}

# Group Offer

## GET /v1/offers(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + offer (optional, string, `{}`) ...
    + ids (optional, string, `9547a14e-027c-415e-884a-5f3a8fc7acda`) ...
    + filter (optional, string, `{"offer_locations_location_id_eq"=>"53b5b8ff-faae-4ea4-b789-01adc3fc1f1b"}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"552add3c91318aa009dd8055a0fe3d82"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 91466289-5ebc-4d3f-81fe-2dbaa56d9c49
            X-Runtime: 0.203334
            Content-Length: 422

    + Body

            {"data":[{"id":"df39e1b1-b589-4c19-9a5e-d12ab32bf9f6","type":"offers","attributes":{"email":"","confirmed":true},"relationships":{"locations":{"links":{"related":"http://www.example.com/v1/locations?filter%5Boffer_locations_offer_id_eq%5D=df39e1b1-b589-4c19-9a5e-d12ab32bf9f6"}},"offer-times":{"links":{"related":"http://www.example.com/v1/offer_times?filter%5Blocation_id_eq%5D=df39e1b1-b589-4c19-9a5e-d12ab32bf9f6"}}}}]}

## POST /v1/offers(.{format})

+ Parameters

    + data (optional, string, `{"type"=>"offers", "attributes"=>{"email"=>"thalia@howell.ca"}, "relationships"=>{"locations"=>{"data"=>[{"type"=>"locations", "id"=>"6289e84d-21b4-4309-919c-28c592d1a030"}]}, "offer-times"=>{"data"=>[{"type"=>"offer-times", "attributes"=>{"time"=>"2013-05-06 00:00:00 +0000"}}]}}}`) ...
    + offer (optional, string, `{}`) ...

+ Request

    + Headers


    + Body

            {"data":{"type":"offers","attributes":{"email":"thalia@howell.ca"},"relationships":{"locations":{"data":[{"type":"locations","id":"6289e84d-21b4-4309-919c-28c592d1a030"}]},"offer-times":{"data":[{"type":"offer-times","attributes":{"time":"2013-05-06 00:00:00 +0000"}}]}}}}

+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"9667e5ee71d472c105cc0552123d2215"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 5dc0dbea-4db6-40f3-9e19-ffed3ab68128
            X-Runtime: 0.024214
            Content-Length: 421

    + Body

            {"data":{"id":"6cf02bf1-513f-487d-86ad-a8e07c15fe3e","type":"offers","attributes":{"email":"","confirmed":false},"relationships":{"locations":{"links":{"related":"http://www.example.com/v1/locations?filter%5Boffer_locations_offer_id_eq%5D=6cf02bf1-513f-487d-86ad-a8e07c15fe3e"}},"offer-times":{"links":{"related":"http://www.example.com/v1/offer_times?filter%5Blocation_id_eq%5D=6cf02bf1-513f-487d-86ad-a8e07c15fe3e"}}}}}

+ Response 422

    is unprocessable

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            Cache-Control: no-cache
            X-Request-Id: ce67c07c-7136-4849-b420-5c7d8f45eb56
            X-Runtime: 0.056837
            Content-Length: 188

    + Body

            {"errors":[{"source":{"pointer":"/data/attributes/email"},"detail":{"message":"blank","meta":{}}},{"source":{"pointer":"/data/attributes/email"},"detail":{"message":"invalid","meta":{}}}]}

## GET /v1/offers/{id}(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + id (required, string, `8faf314e-c713-4fea-9c5f-c34f264d0555`) ...
    + offer (optional, string, `{}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"f9c5c7bd74c4a9e095f4991df6296476"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 8a3eda8a-5751-47ef-a61e-a47456e66afc
            X-Runtime: 0.030572
            Content-Length: 420

    + Body

            {"data":{"id":"8faf314e-c713-4fea-9c5f-c34f264d0555","type":"offers","attributes":{"email":"","confirmed":true},"relationships":{"locations":{"links":{"related":"http://www.example.com/v1/locations?filter%5Boffer_locations_offer_id_eq%5D=8faf314e-c713-4fea-9c5f-c34f264d0555"}},"offer-times":{"links":{"related":"http://www.example.com/v1/offer_times?filter%5Blocation_id_eq%5D=8faf314e-c713-4fea-9c5f-c34f264d0555"}}}}}

+ Response 404

    fails for not confirmed records

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            Cache-Control: no-cache
            X-Request-Id: c399e50d-4adb-4c47-8d3e-66f1d6f3c53b
            X-Runtime: 0.055322
            Content-Length: 143

    + Body

            {"status":404,"message":"Couldn't find Offer with 'id'=9568d60e-6717-45d2-8b72-684d4985b287 [WHERE (\"offers\".\"confirmed_at\" IS NOT NULL)]"}

## PATCH /v1/offers/{id}/confirm(.{format})

+ Parameters

    + token (optional, string, `EbmfEvXZteVRjRFP`) ...
    + id (required, string, `bc450181-38e2-4e2f-95da-da8eefec3be1`) ...
    + offer (optional, string, `{}`) ...

+ Request

    + Headers


    + Body

            {}

+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"d6ec3a889251f94979f3fd951a392284"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 6cde3395-bd85-40c4-972f-b4c44ac69427
            X-Runtime: 0.042593
            Content-Length: 420

    + Body

            {"data":{"id":"bc450181-38e2-4e2f-95da-da8eefec3be1","type":"offers","attributes":{"email":"","confirmed":true},"relationships":{"locations":{"links":{"related":"http://www.example.com/v1/locations?filter%5Boffer_locations_offer_id_eq%5D=bc450181-38e2-4e2f-95da-da8eefec3be1"}},"offer-times":{"links":{"related":"http://www.example.com/v1/offer_times?filter%5Blocation_id_eq%5D=bc450181-38e2-4e2f-95da-da8eefec3be1"}}}}}

+ Response 422

    fails with invalid token

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            Cache-Control: no-cache
            X-Request-Id: 974cedb9-d5e4-43fa-9a0b-1d96f46257f2
            X-Runtime: 0.042661
            Content-Length: 114

    + Body

            {"errors":[{"source":{"pointer":"/data/attributes/confirmation-token"},"detail":{"message":"invalid","meta":{}}}]}



