FORMAT: 1A
HOST: https://letsintegrate.de/api

# Let's integrate


# Group Location

## GET /v1/locations(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + location (optional, string, `{}`) ...
    + ids (optional, string, `47c47226-c55d-4cf9-813c-15fc1efe901d`) ...
    + filter (optional, string, `{"offer_locations_offer_id_eq"=>"b4fb2d6f-0f65-47d0-8855-5ba50dd897da"}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"0813341876aabdee83a1097957f9a338"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 159b3200-fd6c-4300-a8fc-39e4bb9df22b
            X-Runtime: 0.364977
            Content-Length: 387

    + Body

            {"data":[{"id":"0354450f-e514-4264-904f-6c45d1fbd2b4","type":"locations","attributes":{"name":"Location 01","images":["http://lorempixel.com/800/600/city/1/","http://lorempixel.com/800/600/city/3/"],"slug":"location-01"},"relationships":{"offers":{"links":{"related":"http://www.example.com/v1/offers?filter%5Boffer_locations_location_id_eq%5D=0354450f-e514-4264-904f-6c45d1fbd2b4"}}}}]}

## GET /v1/locations/{id}(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + id (required, string, `14560e05-0c4b-4158-8411-9a2c0fd1800a`) ...
    + location (optional, string, `{}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"3c53fe79f8d15ac0672cb508bcf2a35e"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 5127539c-5dbf-482a-b961-e7636f59f802
            X-Runtime: 0.006037
            Content-Length: 385

    + Body

            {"data":{"id":"14560e05-0c4b-4158-8411-9a2c0fd1800a","type":"locations","attributes":{"name":"Location 05","images":["http://lorempixel.com/800/600/city/1/","http://lorempixel.com/800/600/city/3/"],"slug":"location-05"},"relationships":{"offers":{"links":{"related":"http://www.example.com/v1/offers?filter%5Boffer_locations_location_id_eq%5D=14560e05-0c4b-4158-8411-9a2c0fd1800a"}}}}}

# Group OfferTime

## GET /v1/offer_times(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + offer_time (optional, string, `{}`) ...
    + ids (optional, string, `181bdd9c-e203-4747-bddd-cf76d856b91d`) ...
    + filter (optional, string, `{"offer_id_eq"=>"ddf11e82-c278-4c5b-b16d-4988ab3414ed"}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"c498e8595472ee20f63f95890b3b3dff"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: a5d26e6b-c2d1-4dc0-a6fd-7776427a5f38
            X-Runtime: 0.097792
            Content-Length: 246

    + Body

            {"data":[{"id":"3a0e11a3-1351-4e90-a531-f56e413f28f4","type":"offer-times","attributes":{"time":"2014-12-03T00:00:00.000Z"},"relationships":{"offer":{"links":{"related":"http://www.example.com/v1/offers/1c00ada2-3878-4dd6-8dc1-3262b264a877"}}}}]}

## GET /v1/offer_times/{id}(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + id (required, string, `70d33d43-ddec-404a-815a-3c36b9644f8a`) ...
    + offer_time (optional, string, `{}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"edec8fb17d52d490417f7366b06f2a5e"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 033faeec-a8f6-46e1-b777-26f28438e8e3
            X-Runtime: 0.006378
            Content-Length: 244

    + Body

            {"data":{"id":"70d33d43-ddec-404a-815a-3c36b9644f8a","type":"offer-times","attributes":{"time":"2016-04-06T00:00:00.000Z"},"relationships":{"offer":{"links":{"related":"http://www.example.com/v1/offers/5e17fcaf-5b3f-4b06-bf20-cb008a362f0e"}}}}}

# Group Offer

## GET /v1/offers(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + offer (optional, string, `{}`) ...
    + ids (optional, string, `3abf5d18-1c70-4050-959b-4596c0a46172`) ...
    + filter (optional, string, `{"offer_locations_location_id_eq"=>"c8cd783e-e742-46e5-9383-77e1c7149978"}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"47785ae7e0a9d383768852585fedddea"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: eeaef3d5-43a8-486b-9ae1-82ab5e60e110
            X-Runtime: 0.095497
            Content-Length: 422

    + Body

            {"data":[{"id":"fdd9eaa7-af08-40b2-87f9-b5856406939b","type":"offers","attributes":{"email":"","confirmed":true},"relationships":{"locations":{"links":{"related":"http://www.example.com/v1/locations?filter%5Boffer_locations_offer_id_eq%5D=fdd9eaa7-af08-40b2-87f9-b5856406939b"}},"offer-times":{"links":{"related":"http://www.example.com/v1/offer_times?filter%5Blocation_id_eq%5D=fdd9eaa7-af08-40b2-87f9-b5856406939b"}}}}]}

## POST /v1/offers(.{format})

+ Parameters

    + data (optional, string, `{"type"=>"offers", "attributes"=>{"email"=>"kristian@mckenziehilll.com"}, "relationships"=>{"locations"=>{"data"=>[{"type"=>"locations", "id"=>"24343d9a-cec1-4853-ad5d-dae6cf7abaf1"}]}, "offer-times"=>{"data"=>[{"type"=>"offer-times", "attributes"=>{"time"=>"2015-12-20 00:00:00 +0000"}}]}}}`) ...
    + offer (optional, string, `{}`) ...

+ Request

    + Headers


    + Body

            {"data":{"type":"offers","attributes":{"email":"kristian@mckenziehilll.com"},"relationships":{"locations":{"data":[{"type":"locations","id":"24343d9a-cec1-4853-ad5d-dae6cf7abaf1"}]},"offer-times":{"data":[{"type":"offer-times","attributes":{"time":"2015-12-20 00:00:00 +0000"}}]}}}}

+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"07d229008b76e0f89861d62fa31c06eb"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 7fe163c0-e053-43d1-8c12-942be8de4c01
            X-Runtime: 0.048573
            Content-Length: 421

    + Body

            {"data":{"id":"e36b0879-60b6-4e12-89c7-9e65fca582dc","type":"offers","attributes":{"email":"","confirmed":false},"relationships":{"locations":{"links":{"related":"http://www.example.com/v1/locations?filter%5Boffer_locations_offer_id_eq%5D=e36b0879-60b6-4e12-89c7-9e65fca582dc"}},"offer-times":{"links":{"related":"http://www.example.com/v1/offer_times?filter%5Blocation_id_eq%5D=e36b0879-60b6-4e12-89c7-9e65fca582dc"}}}}}

+ Response 422

    is unprocessable

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            Cache-Control: no-cache
            X-Request-Id: ff21caaa-ca6f-4287-adde-ee93e9e7b438
            X-Runtime: 0.060282
            Content-Length: 188

    + Body

            {"errors":[{"source":{"pointer":"/data/attributes/email"},"detail":{"message":"blank","meta":{}}},{"source":{"pointer":"/data/attributes/email"},"detail":{"message":"invalid","meta":{}}}]}

## GET /v1/offers/{id}(.{format})

+ Parameters

    + {} (optional, string, ``) ...
    + id (required, string, `61c06db1-c91a-4264-93c1-046d01c16dc2`) ...
    + offer (optional, string, `{}`) ...

+ Request

    + Headers


+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"f926f4a23ca212015a69637e84670d38"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 5e3a552e-4672-401e-9828-1e2549b10d04
            X-Runtime: 0.018126
            Content-Length: 420

    + Body

            {"data":{"id":"61c06db1-c91a-4264-93c1-046d01c16dc2","type":"offers","attributes":{"email":"","confirmed":true},"relationships":{"locations":{"links":{"related":"http://www.example.com/v1/locations?filter%5Boffer_locations_offer_id_eq%5D=61c06db1-c91a-4264-93c1-046d01c16dc2"}},"offer-times":{"links":{"related":"http://www.example.com/v1/offer_times?filter%5Blocation_id_eq%5D=61c06db1-c91a-4264-93c1-046d01c16dc2"}}}}}

+ Response 404

    fails for not confirmed records

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            Cache-Control: no-cache
            X-Request-Id: 2d26612b-7d18-4535-b20c-09001dc1c63a
            X-Runtime: 0.046225
            Content-Length: 143

    + Body

            {"status":404,"message":"Couldn't find Offer with 'id'=e989df2a-5a95-40c7-8dd9-9df2b7a12a24 [WHERE (\"offers\".\"confirmed_at\" IS NOT NULL)]"}

## PATCH /v1/offers/{id}/confirm(.{format})

+ Parameters

    + token (optional, string, `cnNKwYItHgSzgW1N`) ...
    + id (required, string, `2a507228-20e0-449c-bddb-806db9360206`) ...
    + offer (optional, string, `{}`) ...

+ Request

    + Headers


    + Body

            {}

+ Response 200

    works

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            ETag: W/"a9e4a2b6586572234856176cebaef8bf"
            Cache-Control: max-age=0, private, must-revalidate
            X-Request-Id: 3fa58cf1-8214-486b-a2a3-236ec6052f63
            X-Runtime: 0.022286
            Content-Length: 420

    + Body

            {"data":{"id":"2a507228-20e0-449c-bddb-806db9360206","type":"offers","attributes":{"email":"","confirmed":true},"relationships":{"locations":{"links":{"related":"http://www.example.com/v1/locations?filter%5Boffer_locations_offer_id_eq%5D=2a507228-20e0-449c-bddb-806db9360206"}},"offer-times":{"links":{"related":"http://www.example.com/v1/offer_times?filter%5Blocation_id_eq%5D=2a507228-20e0-449c-bddb-806db9360206"}}}}}

+ Response 422

    fails with invalid token

    + Headers

            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/vnd.api+json; charset=utf-8
            Cache-Control: no-cache
            X-Request-Id: dde47a60-3da1-45a2-9dce-833751cc37bb
            X-Runtime: 0.027228
            Content-Length: 114

    + Body

            {"errors":[{"source":{"pointer":"/data/attributes/confirmation-token"},"detail":{"message":"invalid","meta":{}}}]}



