db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"

redis:
  image: redis:3

web:
  build: .
  command: rails server --port 3000 --binding 0.0.0.0
  ports:
    - "3000:3000"
  links:
    - db
    - redis
  volumes:
    - .:/usr/src/app
  volumes_from:
    - bundle
  environment:
    - DISABLE_SPRING=true
    # Development-Keys
    - RECAPTCHA_PRIVATE_KEY=6LcI_B8TAAAAALiyxXRYc02WOXnc3seOv4PuD052
    - RECAPTCHA_PUBLIC_KEY=6LcI_B8TAAAAAEoy4Tt3ulT4a-3FFBR6aQGCWPA8

bundle:
  image: letsintegrate_web
  command: echo "I'm a little data container, short and stout..."
  volumes:
    - /usr/local/bundle
